### ISSUE TITLE
Excel_Toolkit: Provide long and short name methods to in cell formulae

### ISSUE THREAD

**Issue by rwemay** [BHoM/Excel_UI#103]
Following https://github.com/BHoM/Excel_Toolkit/pull/99 we are wondering what the cost/complexity would be of providing _both_ short and long name options of accessing methods through the in-cell formulae. It could be formula-explosion.... and/or affect performance depending on scale/ability.

**Comment by awakeman** [comment]
If you look at the performance metrics from #99 you will notice that the registration of the methods is now the longest part of the process. So if that is linearly related to the number of functions registered this could be a performance drain.

Will be worth trying, the profiling instrumentation is still there on `master` so we can easily check.

**Comment by rwemay** [comment]
Ok, how about we target global search first, and keep the formula names to the short version for now - park this/do a quick test on it and report findings here. 

Also, just as an aside (perhaps you can raise a new issue) I think we need to reintroduce a tiny context menu for functions that cannot be performed any other way: e.g. Internalise.

**Comment by awakeman** [comment]
With Global Search implemented is this still relevant? I would suggest that the length of the formula is less of an issue and polluting it with more would probably be a bad idea (coupled with the likely performance hit)

**Comment by awakeman** [comment]
Especially now with the ribbon also, users won't have to type out formulae except once they know what is what. Given the fact that we know formula registration is slow, adding more things to register seems like it would cause more usability issues (performance) than it solves (not having to type out long function names).

@rwemay thoughts?

**Comment by rwemay** [comment]
Agree yes - let's close this. One formula per BHoM function given performance issues. We might revisit if a future version of Excel (O365 x64) fixes slow registration issues.
