### ISSUE TITLE
Excel_Toolkit: FilterRquest does not work

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Excel_UI#109]
I have issue running filter request
it does not work for me, 

![image](https://user-images.githubusercontent.com/26113670/60098238-f24dbb80-974c-11e9-9c24-05b0b1236eb1.png)

**Comment by awakeman** [comment]
I cannot reproduce this, are you still experiencing it?

**Comment by michaldengusiak** [comment]
yes, tested with today's masters and current Excel PR still the same issue. Will need your help with this one. 
![image](https://user-images.githubusercontent.com/26113670/60676504-f5e0f100-9e76-11e9-9b63-1f1025737d58.png)

**Comment by michaldengusiak** [comment]
rebuild all again with current UI and Adapter and works fine,

![image](https://user-images.githubusercontent.com/26113670/60679818-e2d31e80-9e80-11e9-91aa-95aa71959e77.png)
