### ISSUE TITLE
Excel_Toolkit: How to deal with lists

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Excel_UI#111]
I pulled panels and want to get polylines
 but got this warning
![image](https://user-images.githubusercontent.com/26113670/60679546-e4e8ad80-9e7f-11e9-8ef4-5e10b38fe689.png)

**Comment by rwemay** [comment]
Hi @michaldengusiak , this isn't an 'issue' as such - I think more that you aren't sure where to find commands. I think there are another few issues you've raised similarly recently. Would be good to post these either in the Yammer groups (internally) or on the Slack channel (external/open source). Feel free to create an Excel_Toolkit Slack channel for example. 

In the case of lists in Excel, you can use the Query.Reflection.Item method to expand the list. If you have a look at the internal Excel templates we have created (in the script library) you'll see this and a host of other methods that you'll find really useful. I would also recommend that you use one of those templates as a basis for your testing/templating moving forwards (set up to print/legible/scalable etc). Give me a shout tomorrow if you need help finding anything. We should also release some of the templates externally/as samples (minus and company specific logos etc.). 

Also as an aside/related, Excel is quite a different UI compared to Grasshopper and Dynamo, without strong list based actions, so we are intending to expose 'Linq' quite soon, which will give us much more powerful list based methods in Excel formulae - get item, get item by property exists/value, sort lists etc etc etc. There's an open issue in the Reflection engine for this.

**Comment by awakeman** [comment]
Closing since I think Rob's reply covers it.
