### ISSUE TITLE
Excel_Toolkit: Explode not working

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Excel_UI#112]
struggling with explode here

![image](https://user-images.githubusercontent.com/26113670/60679997-9e944e00-9e81-11e9-9bc9-8624e7dead20.png)

![image](https://user-images.githubusercontent.com/26113670/60679982-891f2400-9e81-11e9-98a9-51fb32527bfa.png)

**Comment by awakeman** [comment]
This actually looks like a bug, converting this to a bug issue to fix.
