### ISSUE TITLE
Excel_Toolkit: Push FileAdapter

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Excel_UI#113]
Unable to push to fileadapeter

![image](https://user-images.githubusercontent.com/26113670/60680580-bd93df80-9e83-11e9-9f1c-1844ef76f309.png)

I try to achieve this
![image](https://user-images.githubusercontent.com/26113670/60680716-4e6abb00-9e84-11e9-9052-8f0f7eaea131.png)

**Comment by awakeman** [comment]
Could you provide a test file for this please @michaldengusiak

**Comment by awakeman** [comment]
Can't reproduce this, could you check again? here's a test script: https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Excel_Toolkit/Excel_Toolkit-%23113-FileAdapter?csf=1&e=2asiUh

**Comment by michaldengusiak** [comment]
thanks a lot is working with current version now :)
