### ISSUE TITLE
Excel_Toolkit: Solve all warnings on startup

### ISSUE THREAD

**Issue by rwemay** [BHoM/Excel_UI#114]
The warnings dialogue is still popping up. We need to resolve all the warnings at startup.

**Comment by awakeman** [comment]
Does this need to be on the milestone? The window isn't presented to the user absent an error. I know one of the recurring warnings is that excel is truncating long descriptions, that could be squashed by just truncating them on our end silently.

**Comment by rwemay** [comment]
I would say so... in general I think we need to address all errors and warnings. @al-fisher thoughts? Shouldn't hold up the alpha this morning, but for beta.
