### ISSUE TITLE
Excel_Toolkit: Add UI to Excel to replicate Grasshopper icons/UI, and add an 'Load BHoM' option

### ISSUE THREAD

**Issue by rwemay** [BHoM/Excel_UI#130]
#### Description:

Load BHoM option would allow people to toggle whether BHoM loads by default when loading Excel, or load manually from the UI. If a Workbook with BHoM inside is opened, BHoM should force-load.

**Comment by awakeman** [comment]
Had a go at this yesterday but seemingly registering Formulae from within the WorkbookOpen event crashes Excel so needs some more investigation on how to go about it. The answer is likely to involve some async behaviour which will be a little tricky to get right along side #110.
