### ISSUE TITLE
Excel_Toolkit: double pushing again

### ISSUE THREAD

**Issue by rwemay** [BHoM/Excel_UI#137]
#### Description:

Push caller is pushing twice when the cell with the adapter formula in is being triggered by a 'true/false' reference to another cell. The push caller cell does not have an 'if' statement in. The cell does have nested formula (query.excel.cleanlist), when this is removed it only pushes once. 

#### How to replicate:

See test file. 

#### Expected behaviour:

Objects should be pushed once. 

#### Test file(s):

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Excel_Toolkit/Excel_Toolkit-issue137-Double%20Push?csf=1&e=u33Tmx

**Comment by rwemay** [comment]
@awakeman this does appear to be to do with nested formulae, and I think possibly all cells with nested formulae are running twice. The 'delete' caller in the test script also runs twice as it has a nested formula (reflection.create type from string).

**Comment by awakeman** [comment]
Cannot reproduce on current master, objects are definitely only being pushed once from what I can see on the receiving end.

**Comment by awakeman** [comment]
Any update on this?

**Comment by awakeman** [comment]
@rwemay are you still seeing this issue when you use the BHoM in Excel?

**Comment by rwemay** [comment]
Not for a while, close for now and I'll reopen/create new if it crops up again.
