### ISSUE TITLE
Excel_Toolkit: Unable to complete installation

### ISSUE THREAD

**Issue by peterjamesnugent** [BHoM/Excel_UI#138]
#### Description:

Unable to expose the BHoM to Excel as described in the README.

#### How to replicate:

> Load the add-ins from the options menu. Browse to AppData\Roaming\BHoM\Assemblies and load ExcelDna.IntelliSense.xll and BHoM-AddIn.xll.

The ExcelDna.IntelliSense file is a .dll, and not a .xll. It appears the difference is just the file extension. When loading in to Add-Ins, the following error appears:
![image](https://user-images.githubusercontent.com/30078587/62459202-b0199000-b776-11e9-8481-91056740baea.png)

#### Expected behaviour:

BHoM functionality in Excel.
#### Test file(s):

**N/A**

**Comment by peterjamesnugent** [comment]
Strange, it does seem to still work:
![image](https://user-images.githubusercontent.com/30078587/62459666-e99ecb00-b777-11e9-9711-816be2322f09.png)

Is the IntelliSense not required?

**Comment by awakeman** [comment]
That looks like a hang-up from where we previously had the intellisense plugin installed separately, that is now integrated into the BHoM plugin so it isn't needed. You can remove it from your installed addins to kill the warning.

**Comment by peterjamesnugent** [comment]
Ah okay, we should remove that step from the README too.
