### ISSUE TITLE
Excel_Toolkit: Create testing checklist

### ISSUE THREAD

**Issue by awakeman** [BHoM/Excel_UI#146]
#### Describe the documentation issue:

The wiki should contain a checklist of items to check when testing.

#### What is missing/incorrect?

In light particularly of #141 and #144 there should be a list of features and things to explicitly check when testing an Excel PR along with running existing workbooks and checking they still work as expected. Both of the aforementioned didn't affect the functioning of the Excel toolkit but were UI elements that stopped working silently as a result of a change that affect, primarily, the authorship of new BHoM workbooks.

**Comment by awakeman** [comment]
Made a start here: https://github.com/BHoM/Excel_Toolkit/wiki/Testing-checklist

Will comment again when i think it covers most basics. Naturally it will continue to be a living document and primarily we should be sure to capture regressions that get missed in the future and new features as they are developed.

**Comment by al-fisher** [comment]
Great stuff @awakeman -a quick glance at the WIP certainly going in the right direction! This approach is going to be really helpful! 👍

**Comment by epignatelli** [comment]
From the Sprint Closure call - Moved to 2.5 RC milestone because it is about documentation

**Comment by adecler** [comment]
Closing as now covered by the testing procedures
