### ISSUE TITLE
Internalise Data not working in some cases

### ISSUE THREAD

**Issue by rwemay** [BHoM/Excel_UI#149]
#### Description:

As above. 

#### How to replicate:

 - ~~Create a BHoM object, right click whilst in page break view, and note that the internalise data is not visible in the context menu.~~
 - When data is internalised (in normal view) the hidden sheet is created, however, the cell with the internalised data retains the formula/original entry, such that there is no reference to the internalised data. 

#### Expected behaviour:

 - ~~Internalise data should always be visible in context menu when BHoM is loaded/initialised.~~ 
 - When data is internalised, the cell contents should be replaced such that upstream/referenced changes in the spreadsheet do not cause the cell with internalised data to lose reference.

**Comment by awakeman** [comment]
Reopening this issue for the time being whilst I investigate the second issue. see discussion in #153 

Scheduling for next milestone.

Will close again if the issue originates in another toolkit.

**Comment by awakeman** [comment]
Worth re-testing this given recent changes in Serialiser_Engine.

**Comment by kayleighhoude** [comment]
This is a continuous issue on my end (building off of alphas since the 3.1 milestone)
![image](https://user-images.githubusercontent.com/34316256/80227520-ba88fc00-861b-11ea-889b-72c192f1c367.png)

**Comment by adecler** [comment]
This should be fixed by the UI refactoring PR on Excel (https://github.com/BHoM/Excel_Toolkit/pull/243) as I use a completely different system that doesn't retain the original formula.
