### ISSUE TITLE
Excel_Toolkit: Create wiki

### ISSUE THREAD

**Issue by adecler** [BHoM/Excel_UI#15]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by michaldengusiak** [comment]
yes we should add this ... especially Installation part as with current version I do not know how to install I am missing files in previous location ... any help will be appreciated

**Comment by al-fisher** [comment]
In advance of full Wiki - some instructions at top of [README](https://github.com/BHoM/Excel_Toolkit/blob/master/README.md) and also [samples](https://github.com/BHoM/samples/tree/master/Excel_Toolkit)

**Comment by adecler** [comment]
@awakeman , it would be great to finally action this one. 
The Excel_Toolkit still feels pretty difficult to get into even if one somehow knows about Ctrl+Shift+B

You can use as an example the one I have done a while ago for Grasshopper: https://github.com/BHoM/documentation/wiki/Using-the-BHoM

**Comment by awakeman** [comment]
Started something [here](https://github.com/BHoM/Excel_Toolkit/wiki/Getting-started) definitely needs some screenshots and stuff but it's a start.

**Comment by rwemay** [comment]
Screentogif.exe is a good one for images/screenshots. I would say particularly for Excel wiki to help show the intellisense. Is a free download from the web/needs no admin rights.

**Comment by awakeman** [comment]
This is very open-ended, what's our definition of done for this issue? @al-fisher @rwemay

**Comment by rwemay** [comment]
On the basis that this now exists as MVP if nothing else, happy to close this. We should open new issues when people start using/questioning. I saw you're other post this morning which should help with that, thanks!

**Comment by awakeman** [comment]
Great, thanks.
