### ISSUE TITLE
Enable VBA macros/developer mode programming with BHoM references

### ISSUE THREAD

**Issue by rwemay** [BHoM/Excel_UI#158]
#### Description:

With more users working in Excel to create templates and macros, it would be hugely beneficial to expose the BHoM libraries/functionality through VBA/macros in Excel. Having had a quick look, it seems like this might only be possible by making the libraries 'COM visible' which I think has wider implications/will be difficult. @awakeman do you have time to look into this/have you already? @michaldengusiak FYI.

**Comment by rwemay** [comment]
Just to record a quick study on this, it is relatively quick and easy to get the BHoM to show up by registering for COM interop etc, but it does need admin. Also difficult to build different repos with dependencies... Geometry_Engine for example, won't build with COM interop. The other more difficult thing to do is add the boilerplate necessary for individual classes to show up. This probably needs a wider discussion with @epignatelli , @al-fisher , @adecler /others on the approach to being able to load BHoM in other languages/platforms (like Python). 

![image](https://user-images.githubusercontent.com/15233608/69072631-eaf0bc80-0a23-11ea-9ad4-f52870abdf93.png)

![image](https://user-images.githubusercontent.com/15233608/69072677-fe038c80-0a23-11ea-8e39-cb9c89731c18.png)

![image](https://user-images.githubusercontent.com/15233608/69073209-dd880200-0a24-11ea-8dc9-e74aec6a141e.png)


https://stackoverflow.com/questions/19954001/calling-a-net-library-method-from-vba

**Comment by rwemay** [comment]
@awakeman  have you investigated this any further?

**Comment by rwemay** [comment]
@adecler , see here my earlier research on this. As mentioned, good to expose this so we have another intermediate layer in VBA between users/BHoM, to make very simple click-button workflows with a small amount of VBA.

**Comment by adecler** [comment]
The first thing that comes to mind to avoid the problems above (even if it sounds weird) would be to create a separate dll that exposes the entire BHoM to COM (basically a ComVisible wrapper). I believe we will soon be able to generate such a dll automatically thanks to this quarter's work on rapid development cycle.

Well, we could also obviously create a single COM method that would allow us to execute any BHoM method by passing its name as first argument in a similar style to Invoke but with strings. The problem with that though is the loss of intellisense (and every BHoM object would come out as `object`). We would then have an approach similar to a SASS model in a way.

**Comment by al-fisher** [comment]
@adecler as covered in our discussion offline - will be good to capture some further detailed comments and planning on this issue regarding the alternative approaches to achieving this goal. In simple terms building on the note above outlining advantages/disadvantages or challenges of each approach -
1. the "VBA Adapter" approach as prototyped in WIP on PR [here](https://github.com/BHoM/Excel_Toolkit/pull/283) or 
2. exposure of all BHoM .dlls to COM directly, enabling granular method access and intellisense

As commented on PR here https://github.com/BHoM/Excel_Toolkit/pull/283#issuecomment-792040533 I think the benefit to the Excel VBA Macro developer will be really significant in option 2. The end result meaning we will unlock much more creative use from many more users.

so @adecler can you summarise thoughts and notes based on the work you have done testing wrapping, as will be good to understand any challenges for us as a group to plan best approach.
Initial thought based on previous conversation - I actually think creation of a direct 1:1 mapping of COM enabled dlls, with each dll named the same, but with COM suffix or similar, would be an simpler and elegant solution. The Macro developer can just choose to reference whichever BHoM COM .dlls they want based on the Excel workflow they are building. 
This results in a large number of "duplicate" dlls being created, but I think is fine. And as noted creation of these and keeping in sync will be trivial with CI - and can form part of the installer process.

**Comment by adecler** [comment]
The 1:1 mapping of COM enabled dlls is not a trivial task. First, there's the relatively simple tasks:
- process the source code to inject the necessary COM boiler plate and modify project config to make it COM visible before recompiling it.
- get those dll registered without admin right by producing a tlb file for each 

And then, there's the part I don't know how to fix: COM doesn't want anything to do with generic types. That, unfortunately, incluses thing list `List<>`, `Output<>`, etc. This is likely the reason why rob mentioned some dlls were not compiling (although it might also be other problems). So we cannot just add a `[ComVisible(true)]` before each method and call it a day.

I found the current COM interface from the PR really simple to use when I did the File adapter template. You need to have the source code open on a separate screen to compensate for the lack of intellisense when you start to manually create objects. But that's not something anyone that wrote code in javascript for example will find challenging. After all, this is a feature for advanced users already and will often be the case of VBA code created once and used many times. So we don't need to provide the same level of QoL support we do for the UIs (unless if was easy to provide of course). 

So it would be good to have concrete uses cases that cannot be achieved with the current COM interface.
