### ISSUE TITLE
Removal of ambiguous reference between Reflection.Compute and Serialiser.Compute

### ISSUE THREAD

**Issue by al-fisher** [BHoM/Excel_UI#159]
#### Parent issue(s) or Pull Request(s) causing the changes:

With introduction of new `Compute partial class` in `BH.Engine.Serialiser` as part of this PR: https://github.com/BHoM/BHoM_Engine/pull/1270

The follow error is caused:

>  `Compute` is an ambiguous reference between `BH.Engine.Reflection.Compute` and `BH.Engine.Serialiser.Compute` in Excel_UI

**Comment by al-fisher** [comment]
@adecler @awakeman 
This issue needs to be addressed before https://github.com/BHoM/BHoM_Engine/pull/1270 can be closed out.

**Comment by awakeman** [comment]
OK, looking at this now.
