### ISSUE TITLE
Excel_Toolkit: Resolve warnings

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/Excel_UI#167]
**By 30th November please**

#### Broken rules:
Compiler warnings occur when compiling the toolkit.

#### Suggestions to restore compliance:
Ensure code compiles without any warnings.

**Comment by awakeman** [comment]
I'm not seeing any warnings when building on my machine, @FraserGreenroyd do you have an example of where one is showing up?

**Comment by FraserGreenroyd** [comment]
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2729,5): warning MSB3284: Cannot get the file path for type library "0002e157-0000-0000-c000-000000000046" version 5.3. Library not registered. (Exception from HRESULT: 0x8002801D (TYPE_E_LIBNOTREGISTERED)) [d:\a\1\s\Excel_Toolkit\Excel_UI\Excel_UI.csproj]`

Just the one to be handled here.

**Comment by FraserGreenroyd** [comment]
@awakeman any update on this?

**Comment by awakeman** [comment]
Yeah, looks like the issue is that the Office COM interop libraries aren't present on the build machine, naturally. I'll look into if there is a way to reference it in a way that doesn't generate such a warning.

**Comment by FraserGreenroyd** [comment]
Following review, this issue is closed and the warning will be investigated further but without holding up this repo at this time.
