### ISSUE TITLE
The body of an if should be on a separate line

### ISSUE THREAD

**Issue by adecler** [BHoM/Excel_UI#175]
#### Broken rules:
See title. Having the body of the if on the same line make code more difficult to read for no added benefit. See example below:

![image](https://user-images.githubusercontent.com/16853390/70368329-4bb53b80-18e4-11ea-96b2-5141c9d750ed.png)

@FraserGreenroyd , FYI. As it was more an implicit rule based on common sense than anything, it might be good to have it explicitly stated and checked.

**Comment by rwemay** [comment]
Any progress on this @awakeman ?
