### ISSUE TITLE
Explode of Custom Data Issue

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/Excel_UI#178]
#### Description:
Explode of Custom Data stopping at 24 properties vs exploding all properties
![exceltkissue](https://user-images.githubusercontent.com/34316256/71183873-bb151e80-2246-11ea-92bc-7d7f11b10be6.PNG)

**Comment by rwemay** [comment]
@awakeman , this one's a month old - any progress?

**Comment by adecler** [comment]
Working for me based on an example I understand and can reproduce:

![image](https://user-images.githubusercontent.com/16853390/89865980-4f226480-dbe1-11ea-9c87-694fcc71e042.png)


Can you provide an example I can easily replicate that fails ?

**Comment by kayleighhoude** [comment]
@adecler this one's from 1.5 years ago, it has worked since then. we can close the issue :)
