### ISSUE TITLE
Excel_Toolkit: Opening performance

### ISSUE THREAD

**Issue by rwemay** [BHoM/Excel_UI#192]
#### Description:

Adding this issue here as I think worth re-looking at speed of opening Excel. Now we're a few upgraded version into O365, perhaps there are additional options. It's much better than it was at the worst point, but still fairly laggy and given the potential number of users, worth investigating if there's anything to be done. As far as I know the bottleneck was registering of formulae.

**Comment by adecler** [comment]
This issue has now been fixed by the refactoring of Excel
