### ISSUE TITLE
Dynamically register a formula when needed instead of front-loading all of them 

### ISSUE THREAD

**Issue by adecler** [BHoM/Excel_UI#197]
On my machine, activating the BHoM takes about 45 seconds. Half the time is used to collect the information necessary to generate each formula and compile it. The other half register them through Excel-DNA. If I deactivate the front-loading of the formulas and only leave the initialisation of the global menu, the activation time drops to around 2 seconds.

Given that only a small fraction of the formula set is ever going to be used in a spreadsheet (I have 5000 with the toolkit installed on my machine), wouldn't it be better to register a formula only when they are needed? This means either when they are selected by the user or when opening a spreadsheet containing BHoM formulas.

If we do this, both method registration and intellisense will have to be activated per formula. I am not 100% sure that Excel-DNA is capable of doing that properly in its current state so that will require some investigation. But Excel-DNA is open source so we can always augment it with what we need or try with NetOffice Excel API (that we are already using anyway).

There is also the problem of loosing the auto-completion in the formula bar. To be honest, I don't like the way it works at the moment and find it quite hard to find what I need. Currently, we are also loosing the weighting of the search items (keeping most relevant items at the top) so it makes it even less familiar than what we are used to when searching the BHoM. So I would rather have Ctrl-Shift-B working in the formula bar as well and completely ignore the auto-completion provided by Excel.

@al-fisher  @rwemay  @IsakNaslundBh   FYI

**Comment by rwemay** [comment]
Thanks for looking into this further! 45 seconds sounds even slower than I've experienced (around 25). It definitely needs addressing... 

It would be great to keep intellisense. Personally that is how I interact with the BHoM in Excel and am probably one of the heaviest users at the moment, @IsakNaslundBh  is probably the next historic heavy user - what do you think? Also bear in mind that intellisense/autocomplete is basic UI function of Excel/sheet programs (was using Google sheets this week actually - remarkably similar to Excel!). You wouldn't expect to click a mouse/find an icon/search to sum a few numbers with '=sum('

All that said, if it is a choice between 25/45 seconds loading and intellisense/in-cell formulae, we might just have to live without intellisense. I still think we should not have a solution that impacts load time by anything more than a couple of seconds as a matter of priority.

**Comment by adecler** [comment]
@rwemay , yes, we should definitely keep intellisense. I don't see how anyone would be able to the BHoM in Excel without it. To clarify from my long comment in the issue, here's the TL;DR; version:
- **_Method registration_**: keeping (obviously) but will need some rework with Excel-DNA to get that working on dynamic loading
- **_Intellisense_**: keeping. same as registration, will need some rework
- **_Full list of BHoM methods through `=` in formula bar_**: Not keeping for now at least although there might be some ways to speed that up as discussed in our call

Instead of having absolutely nothing BHoM related registered with the `=`, we could at least register everything that corresponds to a button on the BHoM ribbon. Once something selected, the global menu could show up with the filtered selection for that option (similar to what happens whit the menu created from a link in GH). Obviously once a method is registered once (on first use), it then becomes available in the `=` search.

**Comment by awakeman** [comment]
I did play with this back when first implementing it. The real issue is with opening a saved workbook, all those cells will end up with `#NAME!` errors.

To handle it we need a way to track what formulas are in which cells (including capturing when they change position like when a row/column is inserted/deleted) and find a better way to store all of this information than in a hidden sheet like we do with internalised data at the moment, as raw data in the xslx if possible.

It's simple to do in the first instance, the hard part is loading up from a save. scanning the whole workbook for formulas is a no-go because that is *even slower*.

Without change tracking it can be done: register the serialised MethodInfo on first use but this *will* bloat over time; there needs to be a way of deleting things once they are no longer in use anywhere.

The advantage is that if we do this then it should make it compatible with the upgrader which it currently isn't, particularly if the cell references that use each method are stored and kept up to date.

**Comment by adecler** [comment]
I don't really see a problem with storing the selected `ComponentRequest`s in the hidden sheet. No need to scan the whole workbook. Sure, the hidden sheet solution is not sexy but this is something that we are using already anyway so something to explore later as a whole. `ComponentRequest`s have a tiny footprint so I am not sure why you feel it will be a large amount of information bloating the file.
