### ISSUE TITLE
Dataset Null

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/Excel_UI#203]
#### Description:

Create data formulas are not expanding properly and returning `#NULL!` error.

Prior to #201 these were not returning `#NULL!` but are failing to expand all options.

**Comment by al-fisher** [comment]
FYI @kayleighhoude @awakeman 
Issues need to be self explanatory (even the simplest of one liner descriptions will help) such that the bug or issue makes sense or at very least gives some context for others too. (Others may come across similar now or in future)
Appreciate PR merged and closed now - but please be mindful going forward 😄

**Comment by awakeman** [comment]
thanks @al-fisher i've fleshed it out for posterity
