### ISSUE TITLE
Warning as note added to cell stays even when cell is cleared

### ISSUE THREAD

**Issue by tg359** [BHoM/Excel_UI#207]
#### Description:

Warning as note added to cell stays when cell contents are deleted

#### Steps to reproduce:

- Add a method to a cell that will produce a warning
- Delete the cell
- Note added to cell with original warning stays
- Using "clear all" from toolbar removes this as expected

#### Expected behaviour:

Upon deleting a BHoM method from a cell, the warning associated with it is also removed

#### Test file(s):

Simple to reproduce - I used `=Compute.Climate.ImportEpw?by_String(A1)`

**Comment by adecler** [comment]
Parking this one as I don't really see a solution. Cells are cleared properly as long as it is occupied by a BHoM function but are not cleared by Excel itself when a BHoM formula is removed. We don't have a way to detect that a cell was cleared except by using the global event CellChanged. Given that can be quite computationally costly to run that constantly, I am not convinced that this is worth the trade-off.

**Comment by adecler** [comment]
Closing as parked for over two years
