### ISSUE TITLE
Null on GetProperty

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/Excel_UI#212]
#### Description:
Return of #NULL! when using GetProperty, as opposed to NULL
![excelnullissue](https://user-images.githubusercontent.com/34316256/77099922-1e9c1d00-69eb-11ea-93b0-ca4e42c32023.PNG)

**Comment by awakeman** [comment]
We convert to and from Excel's `#NULL!` error deliberately and always have. In what way is this different to what you expect?

**Comment by kayleighhoude** [comment]
#NULL! disallows the use of formulas, example: an if statement to display one or the other of the above columns from volumes extracted directly from a single property vs extracting the (lxwxh)

**Comment by adecler** [comment]
Kind of agree that #NULL! makes more sense in an Excel environment. Happy to go either way though.
@kayleighhoude , I am not sure I understood your example.

**Comment by kayleighhoude** [comment]
@adecler happy to close this issue :)
