### ISSUE TITLE
Fix or suppress diagnostic display

### ISSUE THREAD

**Issue by rwemay** [BHoM/Excel_UI#218]
#### Description:

Fix or suppress the diagnostic display - below (should we not be trying to avoid loading these - might that help load times also?). In either case, users are now contacting us as they think there is a problem so it needs sorting. 
![image](https://user-images.githubusercontent.com/15233608/78221817-01238480-74bc-11ea-8e97-a43876e533b4.png)

**Comment by al-fisher** [comment]
This is related to https://github.com/BHoM/BHoM_UI/issues/235

**Comment by adecler** [comment]
is this still relevant in the context of the UI refactoring ?
I haven't had those once so curious to see if it still happens for others.
