### ISSUE TITLE
Excel_Toolkit: Excel does not build/install correctly

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Excel_UI#223]
#### Description:

After having build _Excel_Toolkit_ and _BHoM_UI_, nothing shows up in Excel on my machine. @LMarkowski mentioned similar issues on installer (@LMarkowski, please add more if you find it helpful).

Is that a known problem? If so, is there a workaround for that?

**EDIT:** I managed to load the assemblies manually in Excel by going to Options => Add-ins => Manage =>browse the _.dna_ file. After clicking through some diagnostic warning, everything seems to be working fine.

@awakeman @rwemay I have added you as the two best informed - please feel free to unassign/assign someone else as you prefer.

**Comment by rwemay** [comment]
I had this issue some time ago but is working now. Can you try deleting excel from your git and recloning?

**Comment by pawelbaran** [comment]
I was starting from fresh - I did not even have the repo cloned to my machine before this test.

**Comment by rwemay** [comment]
Thanks @pawelbaran , are you both able to install Excel/make it show up via the installer? There may be some registration details for Excel that BHoM_UI is not doing that the installer is - @awakeman ?

**Comment by pawelbaran** [comment]
Yeah, this looks like a registration issue when building from source - would be good to confirm that it does never happen when using installer.

**Comment by awakeman** [comment]
it doesn't register for you when building from source, you have to do it manually. if you have it registered already (like having used the installer) then building from source will update it without additional intervention.

**Comment by pawelbaran** [comment]
That explains a lot, thank you @awakeman. In such case, it could be nice dropping a line on Wiki that building from source requires additional action, preferably explaining how to do that (it took me a while to find out).

My issue has been resolved, so this one can be closed on my end - @LMarkowski please feel free to reopen/open new in case you have similar experiences starting with the installer.
