### ISSUE TITLE
Excel_Toolkit: How excel handles multi-output?

### ISSUE THREAD

**Issue by BingWangUS** [BHoM/Excel_UI#224]
Trying to use some compute method that returns in multi-output, getting NULL! error now.

**Comment by rwemay** [comment]
This should have been tackled in the PR below. https://github.com/BHoM/Excel_Toolkit/pull/183

**Comment by BingWangUS** [comment]
After talking to @awakeman, I understand excel handles null differently from grasshopper. I think the issue is a bit clear now:

When trying to use multi-output, the method is expecting a list as output. I also have some input check in the method, which will return null when the check fails. But when this happens, return null does not work well with multi-output.

**Comment by awakeman** [comment]
Had a chat with bing and believe this to be an issue with the specific method and not an Excel issue.

@BingWangUS if you could confirm that it works upon fixing the issues in the method you were writing that it works as expected then we can close this issue.

**Comment by BingWangUS** [comment]
Have another chat with @awakeman and found there may be an issue with return null in the method, while multi-output is expecting a list. 

This potentially stop the method from recording error message correctly. Andrew will look into this.
