### ISSUE TITLE
Review of Excel Post Build Events

### ISSUE THREAD

**Issue by al-fisher** [BHoM/Excel_UI#225]
Following a clean build (that is one with build folders empty or on fresh clone etc.) and following the standard build order:

1. BHoM_UI then
2. Excel_Toolkit 

There are missing .dlls copied across to %AppData% folder. 
Namely 
`NetOffice.dll`
`OfficeApi.dll`
`...`

This leads to the following error when launching Excel 
![image](https://user-images.githubusercontent.com/15924573/81412341-9eb54800-913b-11ea-843e-400f0b2924c9.png)
and BHoM subsequently not loading.

On the next compilation of BHoM_UI and running its Post Build Events - these .dlls are hovered up.

Suggested fix. 
Mirroring Grasshopper, Excel should be responsible for copy _all_ of its dependaces into the correct place.

These is naturally related to our wider conversation about reviewing of post builds etc. However I would suggest we fix this in isolation first and independent of any wider changes that might occur.

@awakeman @adecler

**Comment by adecler** [comment]
Now fixed after refactoring
