### ISSUE TITLE
Update repo ReadMe.md file

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/Excel_UI#226]
In line with the issue available [here](https://github.com/BHoM/admin/issues/4), please update your repositories ReadMe.md file to match the template provided in the linked admin issue.

Please remember to change any instances of `Robot_Toolkit` in the template to your repository name.

I will comment separately with a specific AppVeyor badge link that should be used for this repo.

When you resolve this issue, please add myself and @al-fisher as reviewers.

**Comment by FraserGreenroyd** [comment]
You will want this badge link for the AppVeyor portion of the ReadMe:

`[![Build status](https://ci.appveyor.com/api/projects/status/8n3kvab8a7e0muxw/branch/master?svg=true)](https://ci.appveyor.com/api/projects/status/excel_toolkit/branch/master)`

[![Build status](https://ci.appveyor.com/api/projects/status/8n3kvab8a7e0muxw/branch/master?svg=true)](https://ci.appveyor.com/api/projects/status/excel_toolkit/branch/master)

**Comment by al-fisher** [comment]
Bumping to this current milestone. Is remaining core repo to have readme updated so good to squash - should be a quick one @adecler @kayleighhoude 

As well as above, also the details regarding AppData and menus etc. are out dated following series of refactorings - so good to update

**Comment by adecler** [comment]
PR raised here: https://github.com/BHoM/Excel_Toolkit/pull/267
