### ISSUE TITLE
Excel_Toolkit: Formulae not stored correctly

### ISSUE THREAD

**Issue by rwemay** [BHoM/Excel_UI#235]
#### Description:

Strange behaviour in the test script linked below - formulae not storing in the components tab correctly when saving/reopening, leading to 'duplicate' errors. Also formulae being dynamically changed to completely different methods on reopen - e.g. from create loadcase method to create type method. 

#### Test file(s):

[Test Script](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Excel_Toolkit/Issues/Issue235-Formulae%20Not%20Storing%20Correctly?csf=1&web=1&e=E4ftn2)

[Test Script - Note dependent toolkit PR](https://burohappold.sharepoint.com/:x:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Tedds_Toolkit/Issues/Tedds_Toolkit-Issue004_Initial%20Prototype/Tedds_Toolkit-Issue004_Initial%20Prototype%20rev%2001.xlsx?d=w03dc98d3a1d24d09af964698836c0bfc&csf=1&web=1&e=9kbYaL)

**Comment by rwemay** [comment]
@IsakNaslundBh , @adecler , FYI, this issue persists, adding another test script to the above, you'll need the relevant toolkit PR built to test the second script. 

I haven't been able to reproduce it reliably.... sometimes the formulae save ok, sometimes I have to go in, clear the BHoM hidden and redo the formulae.

**Comment by adecler** [comment]
@rwemay , can you have another look using the new UI refactoring PR ? 
I am not sure I am clear on what I should expect from the files you shared.

**Comment by adecler** [comment]
from discussion with @rwemay , we agreed to close this
