### ISSUE TITLE
Excel_Toolkit: Inputs Displaying As Args

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/Excel_UI#240]
#### Description:
Inputs to the object below display as "arg1" versus their actual input names.
Appears to be occurring on fragment based objects rather than normal objects (ducts appear fine)
![image](https://user-images.githubusercontent.com/34316256/87594259-b0c2e200-c6ba-11ea-92fb-fead79b52a09.png)

**Comment by adecler** [comment]
It seems Excel is limiting the maximum strig size to 256 characters: https://github.com/Excel-DNA/IntelliSense/issues/72

The solution provided here is not the greatest though so I'll see what I can do once I have done the refactoring of the code.
For reference, the handling of that feature is here: https://github.com/BHoM/Excel_Toolkit/blob/ed4b26f5dabd6f8d3d13e5df9d4d396026ae9dde/Excel_UI/UI/Templates/FormulaDataAccessor.cs#L423

**Comment by adecler** [comment]
Now fixed in the UI refactoring PR using the solution discussed (only keeping the upper case letters of teh argument name and adding the full name at the beginning of the description):

![image](https://user-images.githubusercontent.com/16853390/92448435-2777e980-f1eb-11ea-8b8b-9b3f14e96894.png)
