### ISSUE TITLE
Log file not being written to for Enum and Dataset components in Excel

### ISSUE THREAD

**Issue by al-fisher** [BHoM/Excel_UI#245]
#### Description:

Use of Enum and Dataset components in Excel is not being written to the log file.
To be honest - I have not done an exhaustive test of all components either - so there may be others too.
Good to add to the BHoMAnalytics/incorporated into the UI Test procedures.

#### Steps to reproduce:

Drop an enum and/or dataset into a cell - I did this from the BHoM Ribbon, not ctrl-shift-b menu.
Look in, or look for, Log file.

I tested in Grasshopper and it does seem to work! @adecler so raising here.

**Comment by adecler** [comment]
Ha yes, drop downs work a bit differently in Excel. We can capture when they are created but not after that as it becomes an object entirely under the responsibility of Excel. The drop-down itself only contains a string, not the actual objects. The conversion to BHoM happens within whichever component that take it as input. 

I can still capture the creating of the drop-down. we'll just have to be mindful that it only tells us that the component was created, not how many items it was used. For example, we will not have a new usage entry after reopening the file.

I'll do the PR anyways and we can decide there what we do with it.


**Edit:** In case you are wondering, Dynamo is fine. Both components and dropdowns are funneling through the same `RunCaller` method even in the current state of the code.

**Comment by adecler** [comment]
Saying all this made me realise that drop downs are not actually working after reopening the file since the BHoM objects they reference are not in memory anymore 😕 . Will fix that at the same time.
