### ISSUE TITLE
Excel_Toolkit: Explode Go Deep Function Causing Null

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/Excel_UI#253]
#### Description:
Upon doing an explode on some objects with the GoDeep input set to true, I receive a null result vs it just skipping over it and continuing to give a result.

**Comment by adecler** [comment]
> Upon doing an explode on some objects with the GoDeep input set to true, I receive a null result vs it just skipping over it and continuing to give a result.

Can you give an example of object that generate that behaviour ?
