### ISSUE TITLE
Excel_Toolkit: Perform cleanup of array before pushing

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Excel_UI#26]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by awakeman** [comment]
I think this should be the current behaviour, @IsakNaslundBh can you confirm?

**Comment by IsakNaslundBh** [comment]
Will check if this is fixed!

**Comment by IsakNaslundBh** [comment]
Does not seem to be fixed yet. Getting this error selecting a large range:

![image](https://user-images.githubusercontent.com/22005920/51260964-b3eaee00-19af-11e9-9594-1240b11bb79e.png)

Edit: This is on the current master branch.

**Comment by awakeman** [comment]
OK, Thanks.

**Comment by awakeman** [comment]
Duplicated in #78 and #79, resolved in #80
