### ISSUE TITLE
Error in Placing Object

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/Excel_UI#268]
#### Description:

Upon placement of the Life Cycle Assessment Environmental Product Declaration I received the following 2 errors: 
![image](https://user-images.githubusercontent.com/34316256/101930456-29649680-3ba6-11eb-8f06-f6edff33e212.png)
![image](https://user-images.githubusercontent.com/34316256/101930473-2ec1e100-3ba6-11eb-9281-6bfa11053f1d.png)

Issues have cropped up on this object previously due to its extensive length in characters.
Using Alpha 201211

**Comment by adecler** [comment]
Can you give me more details ? 
I tried tried `GlobalWarmingPotential` method and it is being created without problem.
I also tried EnvironmentProductDeclarationByArea and it seems fine too although I have no idea what input to provide to it.

**Comment by kayleighhoude** [comment]
It's the Life Cycle Assessment Environmental Product Declaration object(s) that cause(s) the issue @adecler 
![image](https://user-images.githubusercontent.com/34316256/102229817-2cb79500-3eba-11eb-9c78-c5cc80fec2fe.png)

**Comment by adecler** [comment]
Can you give me more details please ?
As I said previously, I have already tried `EnvironmentProductDeclarationByArea`. Can you either provide a file or a step by step to reproduce (including specific method you called, inputs you used, etc) ? 

If it's really just a question of creating any of those method regardless of their input, then it works for me. Then it would be great if you could try to run it while Visual Studio is attached to see additional information can be found on the source of the problem.

**Comment by kayleighhoude** [comment]
@adecler I can't provide a file because I can't place the object. 

I put dots next to the specific objects in the screenshot above that will not place (they are not the EnvironmentalProductDeclarationByArea method or any related method, they're objects) they are the `BH.oM.LifeCycleAssessment.MaterialFragments.EnvironmentalProductDeclaration` object and the `BH.oM.LifeCycleAssessment.MaterialFragments.SectorEnvironmentalProductDeclaration` object. They each have 35-40 properties (my guess at why they were having trouble being placed, character limit).

**Comment by adecler** [comment]
Now we're getting somewhere :smile: !
Understand that I am not trying a pain but it is impossible for us to fix a bug if you don't provide the basic information to reproduce it. Even mentioning that those dots were in the picture would have helped. 

Now, the fix I did that time on methods with too many characters can still only solve reasonable cases. After trying to create `BH.oM.LifeCycleAssessment.MaterialFragments.EnvironmentalProductDeclaration`, I get the simplified list of arguments as 
```
[AP], [BC], [D], [DOAR], [DOARFF], [D], [EOLT], [EP], [EEE], [ETE], [FW], [GWP], [HWD], [I], [IS], [LCAP], [L], [M], [MF], [MFER], [NHWD], [NRSF], [ODP], [POCP], [P], [PC], [PCRC], [PENRE], [PENRR], [PERE], [PERT], [PERRM], [RAWD], [RY], [RSF], [SM], [QT], [QTV], [N]
```
This alone is already 267 characters.

I'll be honest with you. I don't think that this is something that needs to be fixed further in Excel. I think that the clear problem here is that those objects are in a dire need of refactoring. @FraserGreenroyd , is that something you could help with ? If not, can you suggest someone ?

**Comment by kayleighhoude** [comment]
@michaelhoehn @FraserGreenroyd not sure that this object could be more concise considering the nature of what it's reporting. The only way that I can think of is by introducing fragments, but that would cause a whole lot of refactoring to LCA Toolkit and all of its datasets.

**Comment by adecler** [comment]
@kayleighhoude , an object doesn't have to be a flat list of properties. Would you write a report without sections and paragraphs ? The same goes for here.
