### ISSUE TITLE
BHoM Excel - Cannot Create .json File with File Adapter and PUSH to File

### ISSUE THREAD

**Issue by WilsonKung** [BHoM/Excel_UI#277]
#### Description:
Using Excel BHoM Beta Version 4.0.1.0, it seems when using File Adapter, I am unable to create the .json file and push objects to .json file. I have no issue with pull from .json file using the File Adapter. 

#### Steps to reproduce:
1. Create File Adapter. Specify folder path and file name.
2. Some demo objects (nodes, bars) push to .json file using File Adapter. 

#### Expected behaviour:
A .json file created in the folder with demo objects in the file.

#### Test file(s):
[210111 WWK BHoM Script.xlsx](https://github.com/BHoM/Excel_Toolkit/files/5794184/210111.WWK.BHoM.Script.xlsx)

**Comment by kayleighhoude** [comment]
@WilsonKung I'm fairly certain this is a function of File Adapter on push (change as of November 11) where when you push, the PushConfig has to be set to useDatasetSerialisation (TRUE). Please close this issue if that ends up working out :)

**Comment by WilsonKung** [comment]
@kayleighhoude Thanks. Yes, so the PUSH need to have the ActionConfig set correctly. This action also necessary when using Grasshopper.

Updated Excel file with ActionConfig in PUSH set to DatasetSerialisatoin (True) and BeautifyJson (False). 
[210111 WWK BHoM Script.xlsx](https://github.com/BHoM/Excel_Toolkit/files/6105197/210111.WWK.BHoM.Script.xlsx)
