### ISSUE TITLE
missing excel BHoM

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Excel_UI#282]
Hi,

I just rebuild the whole BHoM but unable to see the toolkit in excel in AddIns. Are there any extra new steps I should follow?
I got it working under GH...

I am using this version
![image](https://user-images.githubusercontent.com/26113670/109398442-e3150d00-7934-11eb-958c-fab7ec8cfe0f.png)

**Comment by adecler** [comment]
Hi @michaldengusiak , are you using the installer or are you compiling manually ? I would recommend running the installer at least once to make sure the BHoM is registered correctly with Excel. You can download the installer from https://bhom.xyz/ (bottom right of the page).
Can you try the latest version and let me know if you still have the problem ?

**Comment by michaldengusiak** [comment]
yes, correct I got it now after installing BHoM_v4.1.beta.1.msi

![image](https://user-images.githubusercontent.com/26113670/119027008-befa2280-b99d-11eb-981b-312a39579b31.png)
