### ISSUE TITLE
Excel_UI.tlb is not part of the installer

### ISSUE THREAD

**Issue by rolyhudson** [BHoM/Excel_UI#294]
#### Description:
After installing a new alpha Excel_UI.tlb does not exist in the Assemblies folder. 

#### Steps to reproduce:
Install current alpha and check Assemblies folder.

#### Expected behaviour:
Excel_UI.tlb should exist in the Assemblies folder after installation of the BHoM.

**Comment by FraserGreenroyd** [comment]
```
xcopy "$(TargetDir)*.xll"  "C:\ProgramData\BHoM\Assemblies" /Y
xcopy "$(TargetDir)*.dna"  "C:\ProgramData\BHoM\Assemblies" /Y
```

Do these files get included with the installer? If so, this would rule out our theory about it being a filter on `dll` files only?

**Comment by FraserGreenroyd** [comment]
`tlbexp.exe "C:\ProgramData\BHoM\Assemblies\$(TargetName)$(TargetExt)" /out:"C:\ProgramData\BHoM\Assemblies\$(TargetName).tlb"`

Maybe `tlbexp.exe` isn't installed on the VM where the installer build is taking place for this command to run?

**Comment by rolyhudson** [comment]
In Assemblies there are the following after installation

- BHoM-AddIn.dna
- BHoM-AddIn64.dna
- BHoM-AddIn.xll
- BHoM-AddIn64.xll

![Screenshot 2021-05-14 112916](https://user-images.githubusercontent.com/6618854/118258372-aa9ebd00-b4a7-11eb-9f14-b181fc04f5f5.jpg)

**Comment by adecler** [comment]
> Maybe tlbexp.exe isn't installed on the VM where the installer build is taking place for this command to run?

It would be the most likely explanation. @FraserGreenroyd do you mind checking ?

**Comment by FraserGreenroyd** [comment]
As an update to this, I am waiting for IT to confirm the ability to install excel on the VM... I have chased yesterday and today and will be chasing again by email shortly.

**Comment by FraserGreenroyd** [comment]
FYI: @rolyhudson @adecler 

The installer from yesterday onwards should be starting to include this if things are working correctly. I have had an update that Excel is now on the VM so hopefully the `tlbexp.exe` is also there. Could someone test an alpha installer from today onwards and take a look to confirm? I'm on leave this week with limited computer access so I won't get chance to look myself till the weekend or early next week so if someone else is able to take a quick look that'd be great.

**Comment by adecler** [comment]
@FraserGreenroyd , I tried the installer from this morning but it didn't create the tlb file.

**Comment by rolyhudson** [comment]
Same observation from me.

**Comment by FraserGreenroyd** [comment]
Following the discussion and investigation, tomorrows installer should be ok.

@adecler are you happy to run an independent test (I'll run another as well, ran one today and that worked but now want to see the auto-installer) to verify and then we can close this issue if it's coming in :smile:

**Comment by rolyhudson** [comment]
Confirming that for me the Excel_UI.tlb is coming in on installation.
