### ISSUE TITLE
Discussion: Process for pushing/pulling from SQL via SQL_Toolkit + VBA

### ISSUE THREAD

**Issue by tg359** [BHoM/Excel_UI#295]
Marked as a discussion, as this is mostly a dumping ground for thoughts on this related to the BPD workflow.

## Process
This is how I foresee people interacting with flat tables in SQL from Excel, and the process for pulling, modifying and pushing back to the DB might work. Most of these functionalities already exist, but a few of them would be useful to have in the Excel_Toolkit to help speed up the process.:

1. User opens template `Workbook` file (this file contains a list behind the scenes of the objects being handled by this template, stored as string representations of the object names).
2. User enters the `ProjectId` to query from the DB.
3. A `PullFromDatabase` button triggers the following actions:
    
    - For the list of pre-defined BHoM objects, check the SQL DB for a corresponding table? If it doesn't exist then create that table in the DB.
    - For the list of pre-defined BHoM objects, if the `Workbook` does not contain a corresponding `Worksheet` then create that `Worksheet`, and add a `ListObject` to that sheet with headers corresponding with the object being handled.

    - For each BHoM object type:
        - Find all matching records in the corresponding SQL Table that match the given `ProjectId`, and populate the corresponding `ListObject` with those objects and properties.

4. User modifies existing records, or adds a new row of a fixed type to an existing `ListObject`.
5. User adds a new row to a `ListObject` where various BHoM objects of a similar structure (though with different `Enum` properties) are visible:
    - A dropdown listing the possible object types to add to this `ListObject`, and button to trigger creation of a new row and corresponding enums/object enables the creation of multiple BHoM objects. 

6. A `PushToDatabase` button triggers the following actions:
    - For the list of pre-defined BHoM objects, find the `ListObjects` containing those objects in the template.
    - For each BHoM object in each `ListObjects`, dispatch the object to its corresponding SQL Table.

## Helper methods in VBA
- Create a table on a given sheet that has headers based on the given BHoM objects properties (https://docs.microsoft.com/en-us/office/vba/api/excel.listobjects.add)
- Check for existence of a sheet
- Check for existence of a `ListObject` with the same name as a BHoM object type
- Create a dropdown based on a list of BHoM object types
- Add a row to an existing `ListObject` table
- Create a BHoM object in a given cell, to reference adjacent cells in a row of a `ListObject` table
- Pull objects from SQL table
- Push objects to SQL table

## Helper methods in C\#
- Create a SQL Table for a given BHoM object
- Check for existence of a given SQL Table for a BHoM object
- Get all rows of SQL Table for a given `ProjectId` (or a generic method for querying SQL Table by field value)

**Comment by adecler** [comment]
Thanks @tg359 ,

I am not sure I understand the need to dynamically create SQL tables and Excel sheets. If we have a curated list of schemas, those would correspond to a fix set of SQL tables / sheets in the template / object definitions, right ?

To use more concrete example, I see you have the following tables in SQL:
- Carbon
- Certification
- Location
- Meter
- Project

So, each of those should correspond to one Excel sheet in the template, an I correct ?

You mentioned that list might grow. Can you give example on how this might be the case ? It seems to me that it would only happen if the scope of the Building Performance toolkit would grow. Not something that would vary per project.

It would be great if you could also create a draw.io diagram to show how the sheets, SQL tables and BHoM objects all relate together if it is more complex than a one to one relationship. 

@al-fisher , FYI.

**Comment by al-fisher** [comment]
Thanks @adecler @tg359 

Agree - not clear on the need for Pull and generation of tables in excel for the "standard" workflow. This could be a very simple upload as tables are fixed. But indeed I may be missing something.

Thus before continuing definition of the granular helper methods etc. here in GitHub - important to complete the User Story and Workflow mapping - with some good clear diagrams we can all scribble on together.
This will help identify more than one discrete user story - meaning, I would expect - the "standard" workflow to be greatly simplified.
