### ISSUE TITLE
Expand List Spill Issue

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/Excel_UI#313]
#### Description:
Expand list won't work across merged cells (typical formatting is to have cells merged across keeping columns and rows their original size)

If the solution is "that's how Excel works", @rwemay please confirm if you're cool with encouraging not merging cells in order to access this functionality

Merged:
![image](https://user-images.githubusercontent.com/34316256/132400631-0a9b4976-d058-428c-b244-da68a8aa5957.png)

Not Merged:
![image](https://user-images.githubusercontent.com/34316256/132400795-be334bcf-dd1d-48ea-8c4c-25f22a241612.png)

#### Test file(s):
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FExcel%5FToolkit%2FIssue%20313

**Comment by kayleighhoude** [comment]
Spill also occurring with Push component over a merged cell: 
![image](https://user-images.githubusercontent.com/34316256/133792252-d33563f1-bcb6-4c76-adf0-720be335fda5.png)

**Comment by kayleighhoude** [comment]
Both this issue and #315 do not occur when utilising the Query Reflection (list, int32) method, this seems to be exclusively related to the UI functions for Excel (Expand List and Internalise) per testing with @al-fisher

**Comment by kayleighhoude** [comment]
Another unexpected result - I deleted a set of columns and the objects collapsed 
![image](https://user-images.githubusercontent.com/34316256/134377253-613dbd6a-b7d9-4e5e-a74e-10ca02db5f81.png)
 Test file: https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FExcel%5FToolkit%2FIssue%20313

**Comment by alexissantella** [comment]
Spill over merged cell, when unmerged "False" appears in the cell next to push. 
![image](https://user-images.githubusercontent.com/69594663/154145084-54a5efd0-20d1-4a2f-946b-0bbc18b04a76.png)

**Comment by alexissantella** [comment]
Test file for previous comment: https://burohappold.sharepoint.com/:x:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/Excel_Toolkit/Issue%20313/SAMPLE_JANHeadcountReport.xlsx?d=w60426fb4317b4d468c0b26ea25b7ad32&csf=1&web=1&e=rt0qeM

**Comment by adecler** [comment]
>If the solution is "that's how Excel works", @rwemay please confirm if you're cool with encouraging not merging cells in order to access this functionality

Unfortunately, it is how Excel works. If you use a native Excel formula like `SEQUENCE` over merged cells, you will have the exact same error:
![image](https://user-images.githubusercontent.com/16853390/154181289-945625ca-3319-42e3-ac83-9d91cf7b5266.png)

Here's what [Microsoft support has to say about this](https://support.microsoft.com/en-us/office/how-to-correct-a-spill-error-ffe0f555-b479-4a17-a6e2-ef9cc9ad4023):

![image](https://user-images.githubusercontent.com/16853390/154181756-e9a16948-6a98-4839-8598-8953520c23a4.png)

Not the most helpful 😞

**Comment by FraserGreenroyd** [comment]
Based on the above response from @adecler and research into Excel, I agree with @adecler that this is default Excel behaviour and not something we can resolve in Excel Toolkit.

 > Spill over merged cell, when unmerged "False" appears in the cell next to push.

That is expected behaviour as the `false` is the output of the push I suspect, similar to the output seen in Grasshopper when doing a push 😄

**Comment by kayleighhoude** [comment]
![image](https://user-images.githubusercontent.com/34316256/159298558-fe9cdb47-4f18-4eba-8604-719a3c4fb3c7.png)

Follow up on this issue displaying the difference in the Base Query (previously Reflection) per conversation with @al-fisher
