### ISSUE TITLE
Excel Adapter value type error

### ISSUE THREAD

**Issue by RMildiner** [BHoM/Excel_UI#332]
#### Description:

When pulling data from a particular spreadsheet using the Excel Adapter, it fails with the following error.

"
1. This component failed to run properly.
- Error: Cannot convert 'Annual Profile'!I4's value to System.Object
- Occured in  BH.Adapter.Excel.ExcelAdapter.ReadExcel(XLWorkbook workbook, String worksheet, String range, Boolean valuesOnly)
     called from BH.Adapter.Excel.ExcelAdapter.ReadExcel(XLWorkbook workbook, String worksheet, CellRange range, Boolean valuesOnly)
- Are you sure you have the correct type of inputs? Check their description for more details.
"

#### Steps to reproduce:
Excel files and grasshopper network are linked below. Copy the files locally and update the directory location in GH. Toggle the boolen to TRUE to see the error.

#### Expected behaviour:
The above network runs and the data flows between the excel files as required.

#### Test file(s):
[]

(https://burohappold.sharepoint.com/:f:/r/sites/Direction/designtechnology/RandDWishlist/00333_Excel%20Adapter/Issue%20No%20332%20Files?csf=1&web=1&e=yZaYDN)

**Comment by pawelbaran** [comment]
I have looked into this issue, it seems to have been fixed in one of the previous pushed made in Excel_Adapter. I am closing the issue, please feel free to reopen if it reoccurs.
