### ISSUE TITLE
BHoM command initiated by VBA code not working 

### ISSUE THREAD

**Issue by rfczapiewski** [BHoM/Excel_UI#343]
#### Description:
When I want to initiate BHoM formula with VBA macro, it is not working, it gives me #NAME? error in the cell, but when I add this formula by clicking in the BHoM tab it is working result is ExcelErrorNull.
![image](https://user-images.githubusercontent.com/58331183/165732570-0c7cb82c-eb06-491b-8fbe-164be40aaff6.png)

There is a workaround if I first add the formula by clicking (manual initialization of the BHoM formula) then after that, the macro initialization is working. But it is not enough for me because I am creating excel add-in which will create template sheets with BHoM formulas but the BHoM formulas initiated by VBA are not working.

#### Steps to reproduce:
1. Close all excel files - the whole excel application (it is very important to reproduce this issue)
2. Open the file in attachment (BHoM_Bug.xlsm) and click the button "BHOM RUN MACRO"

#### Expected behavior:
3. This will give you in cell D7 #NAME? value but I would expect ExcelErrorNull.

#### Test file(s):

[BHoM_Bug.zip](https://github.com/BHoM/Excel_Toolkit/files/8581835/BHoM_Bug.zip)

**Comment by travispotterBH** [comment]
Hello @rfczapiewski, 

Please ensure that you fill out the required parameters when instantiating the Adapter. You will need a connection string like so: 
![image](https://user-images.githubusercontent.com/96432552/208996909-1223ae4b-c631-47a3-82c3-b594842376fd.png)
![image](https://user-images.githubusercontent.com/96432552/208996932-042ca713-89a1-48ba-b174-c97b2c055bb3.png)

Below is what you get if you do not fill out the required parameters. 
![image](https://user-images.githubusercontent.com/96432552/208997048-a889adff-9a6f-453f-9838-940c84d39fa7.png)

On the macro version: 
If you download the 6.0 Beta(https://bhom.xyz/) you'll find that some modifications have been made that enable VBA commands better. 

For security reasons, I did not look at the file provided by you in the issue report. However, I did re-make my own and got the same results that one would get if you did not fill out the required parameters. Please ensure that  you fill out the required parameters. 
![2022-12-21 15_33_02-Window](https://user-images.githubusercontent.com/96432552/208998272-de3f6701-8bb7-4b0d-89cf-58f86b58fead.png)
