### ISSUE TITLE
Excel_UI: Typo in Internalise data button description

### ISSUE THREAD

**Issue by andrewengh** [BHoM/Excel_UI#352]
When hovering over the 'Internalise data' button in the excel bhom UI ribbon, the description of the button contains a typo. Currently says, 'Save the value of the selected cells so it will **stil lbe** available when the file is reopened.' Needs to be changed to 'Save the value of the selected cells so it will **still be** available when the file is reopened.'
https://github.com/BHoM/Excel_UI/blob/bb382e74bf47b3b9e4e8d912150a1a6d247a420a/Excel_UI/Ribbon/Ribbon.cs#L54
![image](https://user-images.githubusercontent.com/93655890/179790361-a62573f1-0ce2-4e15-b342-f683cd9255ac.png)

![image](https://user-images.githubusercontent.com/93655890/179790414-1b1c669d-df21-4756-9f67-7089c5f524d6.png)

**Comment by FraserGreenroyd** [comment]
@dengh0 please feel free to raise a PR to resolve this, I agree it seems like a good first issue for someone to tackle 😄
