### ISSUE TITLE
Excel not launching after installing BHoM 5.2

### ISSUE THREAD

**Issue by atomczak** [BHoM/Excel_UI#360]
#### Description:
I installed BHoM using the installer for version 5.2 beta on my Windows 10, and since that time, my MS Excel is not launching at all. I see the initial window 'Starting Excel...' but it shuts down when trying to load BHoM libraries. After uninstalling BHoM, the Excel is launching correctly again.

**Comment by travispotterBH** [comment]
@atomczak  are you experiencing this problem after the latest 6.0Beta?

**Comment by albinber** [comment]
Closing this issue for now as later betas hopefully solved the issue. If the problem remains please reopen this issue.
