### ISSUE TITLE
Excel_Toolkit : Adding BHoM navigation to Context Menu

### ISSUE THREAD

**Issue by al-fisher** [BHoM/Excel_UI#45]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by awakeman** [comment]
I believe this will need a supporting change in `BHoM_UI` to handle the Microsoft office context menu types because the `AddToMenu()` methods are typed on that and it's neither a WPF or WinForms menu.

**Comment by awakeman** [comment]
Starting to implement this and it's making me think, to make this work in the current implementation will require an implementation of `SelectorMenu<T, CommandBar>` for working with `Microsoft.Office.Core.CommandBar` along with overloads for `Caller.AddToMenu(CommandBar)` and `Selector<T>.AddToMenu(CommandBar)`. 

This seems a little inelegant and speaks of a flaw in the extensibility of the `SelectorMenu`/`Caller`/`Selector` relationship. They look kind of loosely coupled but are actually very tightly coupled. If one ever wants to extend this behaviour to any new UI framework then they can't just locally create an implementation of `SelectorMenu` and make use of it, they need to add a new dependency and new code to `BHoM_UI` and PR that first. Meaning that project would be subject to growing to support every UI framework its separate dependencies use, in effect creating a 2-way dependency.

@adecler do you have any objection to me making an attempt to decouple this in the process? Or shall we just accept the technical debt for now, add the MS Office dependency to BHoM_UI, and keep an eye on if this comes up a forth time and revisit it then?

**Comment by adecler** [comment]
I have done a quick fix in https://github.com/BHoM/BHoM_UI/pull/55 that should the trick for now.
