### ISSUE TITLE
Excel_Toolkit: Clean up installation process and instructions

### ISSUE THREAD

**Issue by rwemay** [BHoM/Excel_UI#53]
There is a manual step after the installer is run to add the Excel addins. The documentation for this step needs to be re-added tot he read.me, and we ideally would remove this manual step altogether. The post-build files also need to be tidied. @awakeman  please target for next Friday as part of the installer/Excel_Toolkit tidy up. 

![image](https://user-images.githubusercontent.com/15233608/50634271-00f9a980-0f46-11e9-8bff-301f7f8541ac.png)

**Comment by al-fisher** [comment]
@awakeman as just discussed - in advance of resolving the technical challenges and registering the BHoM Plugin as part of the installer - @awakeman to update Excel README/Wiki to reinstate guidelines of how to install

**Comment by awakeman** [comment]
Created some issues, back-referenced, to address this issue with incremental improvement

**Comment by al-fisher** [comment]
Thanks @awakeman

**Comment by awakeman** [comment]
All parts now complete.
