### ISSUE TITLE
Excel_Toolkit: BHoM.List function?

### ISSUE THREAD

**Issue by alexradne** [BHoM/Excel_UI#72]
### Working with `List<T>`
When pulling objects they are returned as a `List<T>`. But in order to use these object you must (as far as I know) first use `=BHoM.Explode()`. But sometimes you want to use the objects without "deconstructing" them. I suggest we implement a method for the Excel UI to simply list the objects as a row or as a column. 

I suggest it to be something like this: `BHoM.List(objects, row = false)` or maybe with an option to list the items with the tagged name or object type, in in front of the objects. 

![image](https://user-images.githubusercontent.com/40766496/52857294-9fb91e80-311e-11e9-9e2b-bc870f505751.png)

**Comment by awakeman** [comment]
One way in the mean time is to use `=Query.Reflection.Item?by_ListOfObject_Int32([list], [index])`.

I'm wary of adding too many Excel exclusive helper methods.

**Comment by alexradne** [comment]
Thank you, that's useful for now!

But I would still argue that it is a very essential part of Excel to have lists populating a row or a column rather than a single cell.

**Comment by awakeman** [comment]
FYI, @alexradne, @rwemay added a `Count` reflection method that allows you to do a formula like this:

```
=IF(ROW()-ROW($A$2) < Query.Reflection.Count?by_ListOfObject($A$1), 
    Query.Reflection.Item?by_ListOfObject_Int32($A$1,ROW()-ROW($A$2)),
    ""
)
```

And then just fill down a long way. Example assumes List is on `A1` and first cell containing that formula is `A2` obviously adjust for actual cells. You can, of course, use `COLUMN()` and fill across instead of down.

**Comment by awakeman** [comment]
I'm closing this for now since i think the above method is more flexible and works well.
