### ISSUE TITLE
Excel_Toolkit: Post build not copying files to Roaming/BHoM

### ISSUE THREAD

**Issue by rwemay** [BHoM/Excel_UI#75]
Assuming this is the correct path, can you fix  @awakeman ?

**Comment by rwemay** [comment]
Actually, sorry the files are copying, but date modified is old - is this correct? 

![image](https://user-images.githubusercontent.com/15233608/55409357-d07fd680-5559-11e9-9aac-f465d1a7a906.png)

**Comment by awakeman** [comment]
Yeah, ExcelDNA generates them and they always seem to come out with that modified date.
