### ISSUE TITLE
Excel_Toolkit - Addin-method to check converts to IObjects instead of all sub interfaces

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Excel_UI#8]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by awakeman** [comment]
No longer relevant after migration to BHoM_UI
