### ISSUE TITLE
Excel_Toolkit: Create test template

### ISSUE THREAD

**Issue by alelom** [BHoM/Excel_UI#84]
Create test template for the Excel_Toolkit.

**Comment by alelom** [comment]
## New template with test data
Sample file with test data saved in the Github sample repository: 
`GitHub\samples\Excel_Toolkit\Loadcases and combinations`

Link to the file:
https://burohappold-my.sharepoint.com/:x:/p/alessio_lombardi/EUV1mYEShxxNiQ2jaRctWGwBlPfdLdwABU6YPpMt9iBQmA?e=KTgNwK

* General tidy up
* General anonymization
* Insertion of anonymized test data
* Rearrangement of the adapter page. Now there are several adapters ready to export (Robot/Etabs/File Adapter). Added "free slots" to append other adapters with instructions.
* General insertion of instructions with newcomers in mind.

## Additional Notes
Currently tested on my machine and by @IsakNaslundBh .
There is an open issue which @IsakNaslundBh could not replicate. 
The export worked on my machine, then on closing and reopening Excel I could not make it work anymore. The issue seems to originate in the `Load Cases` sheet from the command:
`Create.Structure.LoadCombination?by_String_Int32_ListOfLoadcase_ListOfDouble_Boolean()`
which now fails constantly. Still trying to track why.

**Comment by awakeman** [comment]
Have you pressed `Ctrl`+`Alt`+`F9` to recompute the sheet after first opening?

**Comment by alelom** [comment]
Embarrassingly no, I didn't, and that fixes that.

Thanks for your help Andrew!

**Comment by awakeman** [comment]
:+1:
