### ISSUE TITLE
Excel_Toolkit: Startup performance

### ISSUE THREAD

**Issue by awakeman** [BHoM/Excel_UI#85]
Just dropping here to investigate in the near future. Would be good to improve the performance of opening excel. The poor performance relative to the other UIs is owing to the fact that we need to wrap each method/type/etc. in an Ecxel formula from startup time as opposed to just enumerating all possibilities into a menu, to be dealt with on-demand.

There may be a way we can do it smarter.

**Comment by michaldengusiak** [comment]
yes this is super slow right now... I hope you can make some difference here :)

**Comment by rwemay** [comment]
Bumping this up again, as it's costing quite a bit of time testing/using as start-up is so slow. Ideas as chatted just now:

1. Write a file somewhere that serialises all of the info for the formulae and loads them from there.
2. Add a UI to allow users to load the BHoM tools (with options for different disciplines) _after_ Excel loads. 

I don't think we should explore option 2 before we try option 1 a) because it means us adding UI and b) I think this is a longer term function and should be coordinated across all UI's - the ability to selectively turn off/on different BHoM functions and namespaces.

**Comment by awakeman** [comment]
Done some investigation on this. Not sure how much we can improve performance with a cache of the methods since the reflection part doesn't appear that expensive, the actual registration API call is the bigger drain, will profile to get some actual data on that, there may be some marginal gains that can be made there but i am doubtful of a meaningful reduction that would actually make it start in under 10-20 seconds. Discussing with Al we agreed that even given reasonable gains in loading that the problem would grow as the BHoM grows, meaning it will only be kicking the can down the road, worth doing still but isn't really a long-term scaleable solution. 

Some amount of user control of which libraries are installed and/or which ones load by default could help.

Options that i have thought of and will experiment with are:

- Don't actually register any methods on startup, do so on demand when a user selects one from the dropdown menu.
  The drawback, or maybe not a drawback depending on your perspective, here is that initially there will be no BHoM related formulae on startup, so you would have to go via the dropdown menu or the global search (when implemented #56).
  This is an analogue of what Grasshopper does.
  We will need to serialise out which methods are used by the sheet so that we can register them preemptively when opening a saved document but that should be a considerably smaller list than the full set so should not be a performance drain.
- Load the BHoM in a background thread, if possible, so that vanilla excel is available quickly and the rest follows, this only makes a big difference for instances that excel is opened without the user intending to use the BHoM, if you need BHoM stuff you'd still have to wait (could be improved with aforementioned marginal gains).
- Pair up the 2 above: load in the background but force on demand loading until the point that they are registered.

As above a longer term plan might be to provide some UI to load individual dlls/toolkits per user request and a means for them to select which ones load by default (a config file driven from the UI).

I'll run some experiments with the above to see what can be achieved I'm not sure some cache will improve performance substantially but will at least profile things to see if I am likely to be right.

Lazy loading coupled with background loading seems a good all-round solution to give everyone, heavy BHoM users and everyone else, a good experience.

**Comment by awakeman** [comment]
Done some profiling today and it's flipped the above on its head, the performance issue is actually populating the context menus. There are 5 context menus to populate for each BHoM Component type (Create, Query, Compute, etc.) and doing so seems relatively slow. The good thing is that we can do that after excel is open since the formulas work without the context menu being populated. I have an initial first draft of this which I will push imminently, however it does cause the operation of Excel to be a little sluggish for a while whilst it does, so it is still very much a work in progress.
