### ISSUE TITLE
Excel_Toolkit: Excel Template installation running question 

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Excel_UI#87]
I appreciate your help. 
I reinstall full BHoM, 
then in excel Add-ins added `BHoM Add-in`

I opened Excel template and try to run... I can see we need to have access to ports
![image](https://user-images.githubusercontent.com/18450341/56120467-0ebbc380-5f66-11e9-937b-9178e87eaedc.png)

I tried to pull data but got some warning.. do we need to set any additional settings?
How do we define that data come from spaces or other objects? I set up Spaces

![image](https://user-images.githubusercontent.com/26113670/56084361-02325080-5e2a-11e9-897c-a0697fcd457f.png)

![image](https://user-images.githubusercontent.com/26113670/56084404-900e3b80-5e2a-11e9-8c83-9892e8fdf3cd.png)

**Comment by awakeman** [comment]
This is more of an issue with Socket_Toolkit, or windows itself really. Windows wants admin permissions to open any port even on a loopback interface (localhost). This would be the same the first time you run Revit, Dynamo or Grasshopper (unless they were already given port opening privileges prior to that) and use the Socket_Toolkit. @turneralex4 Would be good to know if there is a way that we can grant this permission without needing users to get admin permission when they first use the BHoM.

**Comment by awakeman** [comment]
May actually be wrong there, might not require if it only listens on localhost but presently we listen on all addresses:

```cs 
m_Listener = new TcpListener(IPAddress.Any, m_Port);
```

 I'll raise an issue over there to discuss and close this one as it's not an Excel_Toolkit issue.
