### ISSUE TITLE
Excel_Toolkit: Null items in list when merged cells are selected as list input

### ISSUE THREAD

**Issue by rwemay** [BHoM/Excel_UI#97]
When merged cells are selected (e.g. a number of rows of data whose columns are merged), the list should not have nulls. I believe this worked before we updated to null if cell is blank(?)

**Comment by awakeman** [comment]
@rwemay could you provide a test file to reproduce this please.

**Comment by rwemay** [comment]
Test file is below, however, I think this relates to the method/constructor (multistorey) rather than Excel_Toolkit - passing in lists with null items returns null. Is it expected that an empty cell, or a cell with "" (empty string) should return a null? 

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Excel_Toolkit/Excel_Toolkit-Issue97-Null%20causing%20lists%20to%20fail?csf=1&e=bUg1kB

**Comment by awakeman** [comment]
@rwemay yeah, that is expected, are you still having an issue with this or have you dealt with it on the other side now? 

You may want to make use of `=Query.Excel.CleanList?by_ListOfObject()`

**Comment by awakeman** [comment]
As this is expected behaviour now (see #91, #92, #78, #79, #80) I'm going to close this issue.
